<?php

namespace hermes\services;

/**
 * @service GamesService
 */
class GamesService extends AbstractService {

	/**
	 * @api
	 */
	public function getGames() {
		$json = '[
        {
            "GameID": 11381,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/25\/2016",
            "DateTime": "9\/25\/2016 1:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "CBJ",
            "HomeTeam": "STL",
            "AwayTeamID": 16,
            "HomeTeamID": 20,
            "StadiumID": 25,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 3,
            "HomeTeamScore": 7,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011381,
            "GlobalAwayTeamID": 30000016,
            "GlobalHomeTeamID": 30000020,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11382,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/25\/2016",
            "DateTime": "9\/25\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "STL",
            "HomeTeam": "CBJ",
            "AwayTeamID": 20,
            "HomeTeamID": 16,
            "StadiumID": 6,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 5,
            "HomeTeamScore": 0,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011382,
            "GlobalAwayTeamID": 30000020,
            "GlobalHomeTeamID": 30000016,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11383,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 6:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "OTT",
            "HomeTeam": "TOR",
            "AwayTeamID": 5,
            "HomeTeamID": 7,
            "StadiumID": 27,
            "Channel": "TSN4",
            "Attendance": null,
            "AwayTeamScore": 6,
            "HomeTeamScore": 3,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011383,
            "GlobalAwayTeamID": 30000005,
            "GlobalHomeTeamID": 30000007,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11384,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "F\/OT",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "CBJ",
            "HomeTeam": "BOS",
            "AwayTeamID": 16,
            "HomeTeamID": 1,
            "StadiumID": 3,
            "Channel": "NESN",
            "Attendance": null,
            "AwayTeamScore": 3,
            "HomeTeamScore": 2,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011384,
            "GlobalAwayTeamID": 30000016,
            "GlobalHomeTeamID": 30000001,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11385,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "MIN",
            "HomeTeam": "BUF",
            "AwayTeamID": 23,
            "HomeTeamID": 2,
            "StadiumID": 4,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 1,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011385,
            "GlobalAwayTeamID": 30000023,
            "GlobalHomeTeamID": 30000002,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11386,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "PHI",
            "HomeTeam": "NJ",
            "AwayTeamID": 13,
            "HomeTeamID": 10,
            "StadiumID": 18,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 0,
            "HomeTeamScore": 2,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011386,
            "GlobalAwayTeamID": 30000013,
            "GlobalHomeTeamID": 30000010,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11387,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "PHI",
            "HomeTeam": "NYI",
            "AwayTeamID": 13,
            "HomeTeamID": 11,
            "StadiumID": 19,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 0,
            "HomeTeamScore": 3,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011387,
            "GlobalAwayTeamID": 30000013,
            "GlobalHomeTeamID": 30000011,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11388,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "F\/OT",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "CAR",
            "HomeTeam": "WAS",
            "AwayTeamID": 9,
            "HomeTeamID": 15,
            "StadiumID": 29,
            "Channel": "CSMA",
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 1,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011388,
            "GlobalAwayTeamID": 30000009,
            "GlobalHomeTeamID": 30000015,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11389,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 7:30:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "NJ",
            "HomeTeam": "MON",
            "AwayTeamID": 10,
            "HomeTeamID": 4,
            "StadiumID": 16,
            "Channel": "RDS",
            "Attendance": null,
            "AwayTeamScore": 3,
            "HomeTeamScore": 2,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011389,
            "GlobalAwayTeamID": 30000010,
            "GlobalHomeTeamID": 30000004,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11390,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 8:30:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "STL",
            "HomeTeam": "DAL",
            "AwayTeamID": 20,
            "HomeTeamID": 18,
            "StadiumID": 10,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 1,
            "HomeTeamScore": 3,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011390,
            "GlobalAwayTeamID": 30000020,
            "GlobalHomeTeamID": 30000018,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11391,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 9:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "EDM",
            "HomeTeam": "CGY",
            "AwayTeamID": 25,
            "HomeTeamID": 24,
            "StadiumID": 7,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 1,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011391,
            "GlobalAwayTeamID": 30000025,
            "GlobalHomeTeamID": 30000024,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11392,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 9:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "CGY",
            "HomeTeam": "EDM",
            "AwayTeamID": 24,
            "HomeTeamID": 25,
            "StadiumID": 12,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 4,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011392,
            "GlobalAwayTeamID": 30000024,
            "GlobalHomeTeamID": 30000025,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11393,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 10:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "LA",
            "HomeTeam": "ARI",
            "AwayTeamID": 26,
            "HomeTeamID": 29,
            "StadiumID": 2,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 3,
            "HomeTeamScore": 5,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011393,
            "GlobalAwayTeamID": 30000026,
            "GlobalHomeTeamID": 30000029,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11394,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/26\/2016",
            "DateTime": "9\/26\/2016 10:30:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "ARI",
            "HomeTeam": "LA",
            "AwayTeamID": 29,
            "HomeTeamID": 26,
            "StadiumID": 14,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 3,
            "HomeTeamScore": 4,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011394,
            "GlobalAwayTeamID": 30000029,
            "GlobalHomeTeamID": 30000026,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11396,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "F\/OT",
            "Day": "9\/27\/2016",
            "DateTime": "9\/27\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "OTT",
            "HomeTeam": "BUF",
            "AwayTeamID": 5,
            "HomeTeamID": 2,
            "StadiumID": 4,
            "Channel": "WPCW",
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 3,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011396,
            "GlobalAwayTeamID": 30000005,
            "GlobalHomeTeamID": 30000002,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11395,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/27\/2016",
            "DateTime": "9\/27\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "NAS",
            "HomeTeam": "FLA",
            "AwayTeamID": 21,
            "HomeTeamID": 8,
            "StadiumID": 13,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 1,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011395,
            "GlobalAwayTeamID": 30000021,
            "GlobalHomeTeamID": 30000008,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11397,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/27\/2016",
            "DateTime": "9\/27\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "NYI",
            "HomeTeam": "NYR",
            "AwayTeamID": 11,
            "HomeTeamID": 12,
            "StadiumID": 20,
            "Channel": "MSG",
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 5,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011397,
            "GlobalAwayTeamID": 30000011,
            "GlobalHomeTeamID": 30000012,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11398,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/27\/2016",
            "DateTime": "9\/27\/2016 7:00:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "NYI",
            "HomeTeam": "PHI",
            "AwayTeamID": 11,
            "HomeTeamID": 13,
            "StadiumID": 22,
            "Channel": "TCN",
            "Attendance": null,
            "AwayTeamScore": 0,
            "HomeTeamScore": 4,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011398,
            "GlobalAwayTeamID": 30000011,
            "GlobalHomeTeamID": 30000013,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11399,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/27\/2016",
            "DateTime": "9\/27\/2016 7:30:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "PIT",
            "HomeTeam": "DET",
            "AwayTeamID": 14,
            "HomeTeamID": 3,
            "StadiumID": 11,
            "Channel": null,
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 4,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011399,
            "GlobalAwayTeamID": 30000014,
            "GlobalHomeTeamID": 30000003,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        },
        {
            "GameID": 11400,
            "Season": 2017,
            "SeasonType": 2,
            "Status": "Final",
            "Day": "9\/27\/2016",
            "DateTime": "9\/27\/2016 7:30:00 PM",
            "Updated": "10\/6\/2016 10:17:33 AM",
            "IsClosed": true,
            "AwayTeam": "WAS",
            "HomeTeam": "MON",
            "AwayTeamID": 15,
            "HomeTeamID": 4,
            "StadiumID": 16,
            "Channel": "CSMA",
            "Attendance": null,
            "AwayTeamScore": 2,
            "HomeTeamScore": 5,
            "Period": null,
            "TimeRemainingMinutes": null,
            "TimeRemainingSeconds": null,
            "AwayTeamMoneyLine": null,
            "HomeTeamMoneyLine": null,
            "PointSpread": null,
            "OverUnder": null,
            "GlobalGameID": 30011400,
            "GlobalAwayTeamID": 30000015,
            "GlobalHomeTeamID": 30000004,
            "PointSpreadAwayTeamMoneyLine": null,
            "PointSpreadHomeTeamMoneyLine": null,
            "LastPlay": null
        }]';
		$result = json_decode( $json );
		return $result;
	}
}
